// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mcmc_running
int mcmc_running(std::vector< std::string > argv);
RcppExport SEXP mcPAFit_mcmc_running(SEXP argvSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector< std::string > >::type argv(argvSEXP);
    __result = Rcpp::wrap(mcmc_running(argv));
    return __result;
END_RCPP
}
