# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.estimate_alpha_core <- function(a, b, c, d) {
    .Call('mcPAFit_estimate_alpha_core', PACKAGE = 'mcPAFit', a, b, c, d)
}

