# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.mcmc_running <- function(argv) {
    .Call('mcPAFit_mcmc_running', PACKAGE = 'mcPAFit', argv)
}

